name: deploy-ui
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [build-ui]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ui
          workflow: build-ui.yml

      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
